
package com.yinhai.common.webservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.4.4
 * 2021-07-12T11:45:05.503+08:00
 * Generated source version: 3.4.4
 */

@WebFault(name = "UnsupportedEncodingException", targetNamespace = "http://webservice.common.yinhai.com/")
public class UnsupportedEncodingException_Exception extends Exception {

    private com.yinhai.common.webservice.UnsupportedEncodingException faultInfo;

    public UnsupportedEncodingException_Exception() {
        super();
    }

    public UnsupportedEncodingException_Exception(String message) {
        super(message);
    }

    public UnsupportedEncodingException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public UnsupportedEncodingException_Exception(String message, com.yinhai.common.webservice.UnsupportedEncodingException unsupportedEncodingException) {
        super(message);
        this.faultInfo = unsupportedEncodingException;
    }

    public UnsupportedEncodingException_Exception(String message, com.yinhai.common.webservice.UnsupportedEncodingException unsupportedEncodingException, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = unsupportedEncodingException;
    }

    public com.yinhai.common.webservice.UnsupportedEncodingException getFaultInfo() {
        return this.faultInfo;
    }
}
