package com.yinhai.common.webservice;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.4.4
 * 2021-07-12T11:45:05.525+08:00
 * Generated source version: 3.4.4
 */
@WebServiceClient(name = "YinHaiBusiness",
        wsdlLocation = "http://117.176.19.138:9015/nlzcpt/services/yinHaiBusiness?wsdl",
        targetNamespace = "http://webservice.common.yinhai.com/")
public class YinHaiBusinessService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://webservice.common.yinhai.com/", "YinHaiBusiness");
    public final static QName YinHaiBusinessImplPort = new QName("http://webservice.common.yinhai.com/", "YinHaiBusinessImplPort");

    static {
        URL url = null;
        try {
            url = new URL("http://117.176.19.138:9015/nlzcpt/services/yinHaiBusiness?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(YinHaiBusinessService.class.getName())
                    .log(java.util.logging.Level.INFO,
                            "Can not initialize the default wsdl from {0}", "http://117.176.19.138:9015/nlzcpt/services/yinHaiBusiness?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public YinHaiBusinessService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public YinHaiBusinessService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public YinHaiBusinessService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public YinHaiBusinessService(WebServiceFeature... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public YinHaiBusinessService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public YinHaiBusinessService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }


    /**
     * @return returns YinHaiBusiness
     */
    @WebEndpoint(name = "YinHaiBusinessImplPort")
    public YinHaiBusiness getYinHaiBusinessImplPort() {
        return super.getPort(YinHaiBusinessImplPort, YinHaiBusiness.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns YinHaiBusiness
     */
    @WebEndpoint(name = "YinHaiBusinessImplPort")
    public YinHaiBusiness getYinHaiBusinessImplPort(WebServiceFeature... features) {
        return super.getPort(YinHaiBusinessImplPort, YinHaiBusiness.class, features);
    }

}
