package com.yinhai.common.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.4
 * 2021-07-12T11:45:05.517+08:00
 * Generated source version: 3.4.4
 *
 */
@WebService(targetNamespace = "http://webservice.common.yinhai.com/", name = "YinHaiBusiness")
@XmlSeeAlso({ObjectFactory.class})
public interface YinHaiBusiness {

    @WebMethod
    @RequestWrapper(localName = "callBusinessGzip", targetNamespace = "http://webservice.common.yinhai.com/", className = "com.yinhai.common.webservice.CallBusinessGzip")
    @ResponseWrapper(localName = "callBusinessGzipResponse", targetNamespace = "http://webservice.common.yinhai.com/", className = "com.yinhai.common.webservice.CallBusinessGzipResponse")
    @WebResult(name = "return", targetNamespace = "")
    public byte[] callBusinessGzip(

        @WebParam(name = "inputByte", targetNamespace = "")
        byte[] inputByte
    ) throws UnsupportedEncodingException_Exception;

    @WebMethod
    @RequestWrapper(localName = "callBusiness", targetNamespace = "http://webservice.common.yinhai.com/", className = "com.yinhai.common.webservice.CallBusiness")
    @ResponseWrapper(localName = "callBusinessResponse", targetNamespace = "http://webservice.common.yinhai.com/", className = "com.yinhai.common.webservice.CallBusinessResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String callBusiness(

        @WebParam(name = "inputxml", targetNamespace = "")
        String inputxml
    );

    @WebMethod
    @RequestWrapper(localName = "confirmBusiness", targetNamespace = "http://webservice.common.yinhai.com/", className = "com.yinhai.common.webservice.ConfirmBusiness")
    @ResponseWrapper(localName = "confirmBusinessResponse", targetNamespace = "http://webservice.common.yinhai.com/", className = "com.yinhai.common.webservice.ConfirmBusinessResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String confirmBusiness()
;

    @WebMethod
    @RequestWrapper(localName = "getJylsh", targetNamespace = "http://webservice.common.yinhai.com/", className = "com.yinhai.common.webservice.GetJylsh")
    @ResponseWrapper(localName = "getJylshResponse", targetNamespace = "http://webservice.common.yinhai.com/", className = "com.yinhai.common.webservice.GetJylshResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String getJylsh(

        @WebParam(name = "inputxml", targetNamespace = "")
        String inputxml
    );

    @WebMethod
    @RequestWrapper(localName = "cancelBusiness", targetNamespace = "http://webservice.common.yinhai.com/", className = "com.yinhai.common.webservice.CancelBusiness")
    @ResponseWrapper(localName = "cancelBusinessResponse", targetNamespace = "http://webservice.common.yinhai.com/", className = "com.yinhai.common.webservice.CancelBusinessResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String cancelBusiness()
;

    @WebMethod
    @RequestWrapper(localName = "queryBusiness", targetNamespace = "http://webservice.common.yinhai.com/", className = "com.yinhai.common.webservice.QueryBusiness")
    @ResponseWrapper(localName = "queryBusinessResponse", targetNamespace = "http://webservice.common.yinhai.com/", className = "com.yinhai.common.webservice.QueryBusinessResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String queryBusiness(

        @WebParam(name = "inputxml", targetNamespace = "")
        String inputxml
    );
}
