
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.yinhai.common.webservice;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.4
 * 2021-07-12T11:45:05.508+08:00
 * Generated source version: 3.4.4
 *
 */

@javax.jws.WebService(
                      serviceName = "YinHaiBusiness",
                      portName = "YinHaiBusinessImplPort",
                      targetNamespace = "http://webservice.common.yinhai.com/",
                      wsdlLocation = "http://117.176.19.138:9015/nlzcpt/services/yinHaiBusiness?wsdl",
                      endpointInterface = "com.yinhai.common.webservice.YinHaiBusiness")

public class YinHaiBusinessImplPortImpl implements YinHaiBusiness {

    private static final Logger LOG = Logger.getLogger(YinHaiBusinessImplPortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.yinhai.common.webservice.YinHaiBusiness#callBusinessGzip(byte[] inputByte)*
     */
    public byte[] callBusinessGzip(byte[] inputByte) throws UnsupportedEncodingException_Exception   {
        LOG.info("Executing operation callBusinessGzip");
        System.out.println(inputByte);
        try {
            byte[] _return = new byte[0];
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new UnsupportedEncodingException_Exception("UnsupportedEncodingException...");
    }

    /* (non-Javadoc)
     * @see com.yinhai.common.webservice.YinHaiBusiness#callBusiness(String inputxml)*
     */
    public String callBusiness(String inputxml) {
        LOG.info("Executing operation callBusiness");
        System.out.println(inputxml);
        try {
            String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.yinhai.common.webservice.YinHaiBusiness#confirmBusiness()*
     */
    public String confirmBusiness() {
        LOG.info("Executing operation confirmBusiness");
        try {
            String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.yinhai.common.webservice.YinHaiBusiness#getJylsh(String inputxml)*
     */
    public String getJylsh(String inputxml) {
        LOG.info("Executing operation getJylsh");
        System.out.println(inputxml);
        try {
            String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.yinhai.common.webservice.YinHaiBusiness#cancelBusiness()*
     */
    public String cancelBusiness() {
        LOG.info("Executing operation cancelBusiness");
        try {
            String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.yinhai.common.webservice.YinHaiBusiness#queryBusiness(String inputxml)*
     */
    public String queryBusiness(String inputxml) {
        LOG.info("Executing operation queryBusiness");
        System.out.println(inputxml);
        try {
            String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
